// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5BF_QuLg_PgYXLE46h9rtHcUXN2tQxw',
    appId: '1:431120968271:web:933d1a30eb35f63e4e983a',
    messagingSenderId: '431120968271',
    projectId: 'banking-app-f161c',
    authDomain: 'banking-app-f161c.firebaseapp.com',
    storageBucket: 'banking-app-f161c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTy3KZXEUKlK9egUXgqEKuymuERAA-es',
    appId: '1:431120968271:android:eb2edd46a71f49e74e983a',
    messagingSenderId: '431120968271',
    projectId: 'banking-app-f161c',
    storageBucket: 'banking-app-f161c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRN8V7xcp9leQajneQwNmIIMNrmTWIJE',
    appId: '1:431120968271:ios:c2ffd9f23bf722564e983a',
    messagingSenderId: '431120968271',
    projectId: 'banking-app-f161c',
    storageBucket: 'banking-app-f161c.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRN8V7xcp9leQajneQwNmIIMNrmTWIJE',
    appId: '1:431120968271:ios:c2ffd9f23bf722564e983a',
    messagingSenderId: '431120968271',
    projectId: 'banking-app-f161c',
    storageBucket: 'banking-app-f161c.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz5BF_QuLg_PgYXLE46h9rtHcUXN2tQxw',
    appId: '1:431120968271:web:7c55808debd39b454e983a',
    messagingSenderId: '431120968271',
    projectId: 'banking-app-f161c',
    authDomain: 'banking-app-f161c.firebaseapp.com',
    storageBucket: 'banking-app-f161c.firebasestorage.app',
  );
}
